name: CI/CD Setup

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - main

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch name
        run: |
          BRANCH_NAME="${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}"
          if [[ ! "$BRANCH_NAME" =~ ^feature\/ ]]; then
            echo "❌ ERROR: Branch name must start with 'feature/'"
            exit 1
          fi
          echo "✅ Valid branch name: $BRANCH_NAME"
        shell: bash

  validate:
    runs-on: ubuntu-latest
    needs: check-branch-name
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Build project
        run: npm run build
